server.port=8080

spring.application.name=api-gateway
spring.cloud.gateway.discovery.locator.enabled=true

# Gateway Routes
spring.cloud.gateway.routes[0].id=auth-service-route
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/login

spring.cloud.gateway.routes[1].id=account-service-route
spring.cloud.gateway.routes[1].uri=lb://ACCOUNT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/accounts/**

spring.cloud.gateway.routes[2].id=transaction-service-route
spring.cloud.gateway.routes[2].uri=lb://TRANSACTION-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/transactions/**

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# JWT Secret
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970