server:
  port: 8083

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

account-service:
  url: ${ACCOUNT_SERVICE_URL:http://localhost:8082}

spring:
  application:
    name: transaction-service
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.singkodebangko.transaction: DEBUG
    feign: DEBUG
